### ISSUE TITLE
First screen on Mavericks is messed up

### ISSUE THREAD

**Issue by aokolish** [woollyapp/woolly#4]
Recently, I upgraded to OSX Mavericks and the first screen looks like this:

![pasted_image_10_25_13__10_46_am](https://f.cloud.github.com/assets/705514/1410023/91f7d310-3d9d-11e3-8d03-10a73b41d07b.jpg)

**Comment by kevintom** [comment]
noted.

will be fixed in next build which will address a group of small mavericks issues.

this particular one is cause by a line which turns out layout debugging, but which isn't supposed to do anything on "production" systems.  i dunno why all of a sudden it is turned on in mavericks, but i'll make sure to turn it off.

**Comment by kevintom** [comment]
Fix has been approved and new version has been released
